# Generated by Django 5.1 on 2026-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_land_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='area',
        ),
        migrations.RemoveField(
            model_name='land',
            name='dag_no',
        ),
        migrations.RemoveField(
            model_name='land',
            name='khatian_no',
        ),
        migrations.RemoveField(
            model_name='land',
            name='mouza',
        ),
        migrations.AddField(
            model_name='land',
            name='allocated_plots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='land',
            name='remaining_plots',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='land',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Area in Acres', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='total_plots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
