# Generated by Django 5.1 on 2026-07-07 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_remove_land_area_remove_land_dag_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_verified', models.BooleanField(default=False)),
                ('admin_verified_date', models.DateTimeField(blank=True, null=True)),
                ('super_admin_verified', models.BooleanField(default=False)),
                ('super_admin_verified_date', models.DateTimeField(blank=True, null=True)),
                ('admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_verified_lands', to=settings.AUTH_USER_MODEL)),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='lands.land')),
                ('super_admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admin_verified_lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
