# Generated by Django 5.1 on 2026-08-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_landverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landverification',
            name='admin_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_land_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landverification',
            name='super_admin_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admin_land_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
