# Generated by Django 5.1 on 2026-07-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DATA_ENTRY', 'Data Entry'), ('VIEWER', 'Viewer')], default='DATA_ENTRY', max_length=30),
        ),
    ]
