# Generated by Django 5.1 on 2026-07-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rd_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RD_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_entry_users', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RD_ADMIN', 'Regional Admin'), ('DATA_ENTRY', 'Data Entry'), ('VIEWER', 'Viewer')], default='DATA_ENTRY', max_length=30),
        ),
    ]
