# Generated by Django 5.2.8 on 2025-11-18 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Gazette', 'Gazette'), ('Deed', 'Deed'), ('Khatiyan', 'Khatiyan'), ('Mutation', 'Mutation'), ('Lease Deed', 'Lease Deed'), ('Other', 'Other')], max_length=50)),
                ('document_number', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('scanned_copy', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lands.land')),
            ],
        ),
    ]
