# Generated by Django 5.2.8 on 2025-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Gazette', 'Gazette'), ('Deed', 'Deed'), ('Khatiyan', 'Khatiyan'), ('Mutation', 'Mutation'), ('Lease Deed', 'Lease Deed'), ('Land Tax', 'Land Tax'), ('Other', 'Other')], max_length=50),
        ),
    ]
