# Generated by Django 5.1 on 2026-04-20 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_tag_document_merged_pdf_alter_document_scanned_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='from_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='survey_type',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('SA', 'SA'), ('RS', 'RS'), ('BDS', 'BDS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='to_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Gazette', 'Gazette'), ('Deed (Sale Deed / Registry Deed)', 'Deed (Sale Deed / Registry Deed)'), ('Khatiyan', 'Khatiyan'), ('Mutation (Namjari)', 'Mutation (Namjari)'), ('Lease Deed', 'Lease Deed'), ('Land Tax (Khajna / DCR)', 'Land Tax (Khajna / DCR)'), ('Porcha', 'Porcha'), ('Mouza Map', 'Mouza Map'), ('Baina / Agreement for Sale', 'Baina / Agreement for Sale'), ('Land Survey Report', 'Land Survey Report'), ('Building Plan Approval', 'Building Plan Approval')], max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='documents.document')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
