# Generated by Django 5.1 on 2026-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_from_page_document_survey_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Gazette', 'Gazette'), ('Deed (Sale Deed / Registry Deed)', 'Deed (Sale Deed / Registry Deed)'), ('Khatiyan', 'Khatiyan'), ('Mutation (Namjari)', 'Mutation (Namjari)'), ('Lease Deed', 'Lease Deed'), ('Land Tax (Khajna / DCR)', 'Land Tax (Khajna / DCR)'), ('Porcha', 'Porcha'), ('Mouza Map', 'Mouza Map'), ('Baina / Agreement for Sale', 'Baina / Agreement for Sale'), ('Land Survey Report', 'Land Survey Report'), ('Building Plan Approval', 'Building Plan Approval')], max_length=50),
        ),
    ]
