# Generated by Django 5.1 on 2026-04-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='documents.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='documents.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document', 'tag')},
            },
        ),
    ]
