# Generated by Django 5.1 on 2026-05-14 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTagEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('survey_type', models.CharField(blank=True, max_length=10, null=True)),
                ('from_page', models.PositiveIntegerField(blank=True, null=True)),
                ('to_page', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_entries', to='documents.document')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_entries', to='documents.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
