# Generated by Django 5.1 on 2026-07-02 03:57

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documenttagentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttagentry',
            name='separated_pdf',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.separated_pdf_path),
        ),
    ]
