# Generated by Django 5.1 on 2026-08-30 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_office', models.CharField(max_length=255, verbose_name='RD Office')),
                ('division', models.CharField(max_length=100, verbose_name='Division')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('upazila', models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila')),
                ('office_type', models.CharField(choices=[('আঞ্চলিক কার্যালয়', 'আঞ্চলিক কার্যালয়'), ('জেলা কার্যালয়', 'জেলা কার্যালয়'), ('CIDP কার্যালয়', 'CIDP কার্যালয়'), ('মৌমাছি পালন কর্মসূচি কার্যালয়', 'মৌমাছি পালন কর্মসূচি কার্যালয়'), ('অন্যান্য', 'অন্যান্য')], max_length=100, verbose_name='Office Type')),
                ('office_name', models.CharField(max_length=255, verbose_name='Office Name')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Area (Acres)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_verified', models.BooleanField(default=False)),
                ('admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('super_admin_verified', models.BooleanField(default=False)),
                ('super_admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='another_land_admin_verified', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='another_land_created', to=settings.AUTH_USER_MODEL)),
                ('super_admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='another_land_super_admin_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Another Land',
                'verbose_name_plural': 'Another Lands',
                'ordering': ['district', 'upazila', 'office_name'],
            },
        ),
    ]
