# Generated by Django 5.1 on 2026-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnotherLand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherland',
            name='division',
            field=models.CharField(choices=[('বরিশাল', 'বরিশাল (Barishal)'), ('চট্টগ্রাম', 'চট্টগ্রাম (Chittagong)'), ('ঢাকা', 'ঢাকা (Dhaka)'), ('ময়মনসিংহ', 'ময়মনসিংহ (Mymensingh)'), ('রাজশাহী', 'রাজশাহী (Rajshahi)'), ('রংপুর', 'রংপুর (Rangpur)'), ('সিলেট', 'সিলেট (Shylet)'), ('খুলনা', 'খুলনা (Khulna)')], max_length=100, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='anotherland',
            name='office_type',
            field=models.CharField(choices=[('CIDP কার্যালয়', 'CIDP কার্যালয়'), ('অন্যান্য', 'অন্যান্য'), ('জেলা কার্যালয়', 'জেলা কার্যালয়'), ('মৌমাছি পালন কর্মসূচি কার্যালয়', 'মৌমাছি পালন কর্মসূচি কার্যালয়'), ('আঞ্চলিক কার্যালয়', 'আঞ্চলিক কার্যালয়')], max_length=100, verbose_name='Office Type'),
        ),
        migrations.AlterField(
            model_name='anotherland',
            name='rd_office',
            field=models.CharField(choices=[('বিসিক আঞ্চলিক কার্যালয়, চট্টগ্রাম', 'বিসিক আঞ্চলিক কার্যালয়, চট্টগ্রাম'), ('বিসিক আঞ্চলিক কার্যালয়, ঢাকা', 'বিসিক আঞ্চলিক কার্যালয়, ঢাকা'), ('বিসিক আঞ্চলিক কার্যালয়, খুলনা', 'বিসিক আঞ্চলিক কার্যালয়, খুলনা'), ('বিসিক আঞ্চলিক কার্যালয়, রাজশাহী', 'বিসিক আঞ্চলিক কার্যালয়, রাজশাহী')], max_length=255, verbose_name='RD Office'),
        ),
    ]
