# Generated by Django 5.1 on 2026-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnotherLand', '0002_alter_anotherland_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherland',
            name='admin_verification_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Verification Comment'),
        ),
        migrations.AddField(
            model_name='anotherland',
            name='super_admin_verification_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Super Admin Verification Comment'),
        ),
    ]
